FROM python:3.11

WORKDIR /app

COPY . /app

RUN apt-get update -q \
    && apt-get install -y --no-install-recommends $(cat /app/aptfile || echo "") \
    && rm -rf /var/lib/apt/lists/* \
    && pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir -r test_requirements.txt

ENV PYTHONPATH="/app"

ENTRYPOINT ["/usr/local/bin/python3"]

CMD ["pytest", "--junitxml=/app/tests/test-results.xml"]

